// Generated by gencpp from file amore_vision/buoy.msg
// DO NOT EDIT!


#ifndef AMORE_VISION_MESSAGE_BUOY_H
#define AMORE_VISION_MESSAGE_BUOY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace amore_vision
{
template <class ContainerAllocator>
struct buoy_
{
  typedef buoy_<ContainerAllocator> Type;

  buoy_()
    : centroid()
    , color()
    , label()  {
    }
  buoy_(const ContainerAllocator& _alloc)
    : centroid(_alloc)
    , color(_alloc)
    , label(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point32_<ContainerAllocator>  _centroid_type;
  _centroid_type centroid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _color_type;
  _color_type color;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::amore_vision::buoy_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore_vision::buoy_<ContainerAllocator> const> ConstPtr;

}; // struct buoy_

typedef ::amore_vision::buoy_<std::allocator<void> > buoy;

typedef boost::shared_ptr< ::amore_vision::buoy > buoyPtr;
typedef boost::shared_ptr< ::amore_vision::buoy const> buoyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore_vision::buoy_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore_vision::buoy_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore_vision::buoy_<ContainerAllocator1> & lhs, const ::amore_vision::buoy_<ContainerAllocator2> & rhs)
{
  return lhs.centroid == rhs.centroid &&
    lhs.color == rhs.color &&
    lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore_vision::buoy_<ContainerAllocator1> & lhs, const ::amore_vision::buoy_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::buoy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::buoy_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::buoy_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::buoy_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::buoy_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::buoy_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore_vision::buoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "205d7f01bdec538ed3caf910fa5c88f1";
  }

  static const char* value(const ::amore_vision::buoy_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x205d7f01bdec538eULL;
  static const uint64_t static_value2 = 0xd3caf910fa5c88f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::amore_vision::buoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore_vision/buoy";
  }

  static const char* value(const ::amore_vision::buoy_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore_vision::buoy_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32 centroid\n"
"string color\n"
"string label\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::amore_vision::buoy_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore_vision::buoy_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.centroid);
      stream.next(m.color);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct buoy_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore_vision::buoy_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore_vision::buoy_<ContainerAllocator>& v)
  {
    s << indent << "centroid: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "  ", v.centroid);
    s << indent << "color: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.color);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_VISION_MESSAGE_BUOY_H
