// Generated by gencpp from file amore_vision/depth_points.msg
// DO NOT EDIT!


#ifndef AMORE_VISION_MESSAGE_DEPTH_POINTS_H
#define AMORE_VISION_MESSAGE_DEPTH_POINTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amore_vision
{
template <class ContainerAllocator>
struct depth_points_
{
  typedef depth_points_<ContainerAllocator> Type;

  depth_points_()
    : labeled_point()  {
      labeled_point.assign(0.0);
  }
  depth_points_(const ContainerAllocator& _alloc)
    : labeled_point()  {
  (void)_alloc;
      labeled_point.assign(0.0);
  }



   typedef boost::array<float, 4>  _labeled_point_type;
  _labeled_point_type labeled_point;





  typedef boost::shared_ptr< ::amore_vision::depth_points_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore_vision::depth_points_<ContainerAllocator> const> ConstPtr;

}; // struct depth_points_

typedef ::amore_vision::depth_points_<std::allocator<void> > depth_points;

typedef boost::shared_ptr< ::amore_vision::depth_points > depth_pointsPtr;
typedef boost::shared_ptr< ::amore_vision::depth_points const> depth_pointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore_vision::depth_points_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore_vision::depth_points_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore_vision::depth_points_<ContainerAllocator1> & lhs, const ::amore_vision::depth_points_<ContainerAllocator2> & rhs)
{
  return lhs.labeled_point == rhs.labeled_point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore_vision::depth_points_<ContainerAllocator1> & lhs, const ::amore_vision::depth_points_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::depth_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::depth_points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::depth_points_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::depth_points_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::depth_points_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::depth_points_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore_vision::depth_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "242571970d31da06fb7d6fd8a07d1e48";
  }

  static const char* value(const ::amore_vision::depth_points_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x242571970d31da06ULL;
  static const uint64_t static_value2 = 0xfb7d6fd8a07d1e48ULL;
};

template<class ContainerAllocator>
struct DataType< ::amore_vision::depth_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore_vision/depth_points";
  }

  static const char* value(const ::amore_vision::depth_points_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore_vision::depth_points_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] labeled_point\n"
;
  }

  static const char* value(const ::amore_vision::depth_points_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore_vision::depth_points_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.labeled_point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct depth_points_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore_vision::depth_points_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore_vision::depth_points_<ContainerAllocator>& v)
  {
    s << indent << "labeled_point[]" << std::endl;
    for (size_t i = 0; i < v.labeled_point.size(); ++i)
    {
      s << indent << "  labeled_point[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.labeled_point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_VISION_MESSAGE_DEPTH_POINTS_H
