// Generated by gencpp from file amore_vision/NED_poses.msg
// DO NOT EDIT!


#ifndef AMORE_VISION_MESSAGE_NED_POSES_H
#define AMORE_VISION_MESSAGE_NED_POSES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace amore_vision
{
template <class ContainerAllocator>
struct NED_poses_
{
  typedef NED_poses_<ContainerAllocator> Type;

  NED_poses_()
    : poses()
    , quantity(0)  {
    }
  NED_poses_(const ContainerAllocator& _alloc)
    : poses(_alloc)
    , quantity(0)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _poses_type;
  _poses_type poses;

   typedef int32_t _quantity_type;
  _quantity_type quantity;





  typedef boost::shared_ptr< ::amore_vision::NED_poses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore_vision::NED_poses_<ContainerAllocator> const> ConstPtr;

}; // struct NED_poses_

typedef ::amore_vision::NED_poses_<std::allocator<void> > NED_poses;

typedef boost::shared_ptr< ::amore_vision::NED_poses > NED_posesPtr;
typedef boost::shared_ptr< ::amore_vision::NED_poses const> NED_posesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore_vision::NED_poses_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore_vision::NED_poses_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore_vision::NED_poses_<ContainerAllocator1> & lhs, const ::amore_vision::NED_poses_<ContainerAllocator2> & rhs)
{
  return lhs.poses == rhs.poses &&
    lhs.quantity == rhs.quantity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore_vision::NED_poses_<ContainerAllocator1> & lhs, const ::amore_vision::NED_poses_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::NED_poses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::NED_poses_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::NED_poses_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::NED_poses_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::NED_poses_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::NED_poses_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore_vision::NED_poses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f0ed5e05a989aa92228d75bc8d6fdd0b";
  }

  static const char* value(const ::amore_vision::NED_poses_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf0ed5e05a989aa92ULL;
  static const uint64_t static_value2 = 0x228d75bc8d6fdd0bULL;
};

template<class ContainerAllocator>
struct DataType< ::amore_vision::NED_poses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore_vision/NED_poses";
  }

  static const char* value(const ::amore_vision::NED_poses_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore_vision::NED_poses_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] poses\n"
"int32 quantity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::amore_vision::NED_poses_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore_vision::NED_poses_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
      stream.next(m.quantity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NED_poses_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore_vision::NED_poses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore_vision::NED_poses_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.poses[i]);
    }
    s << indent << "quantity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quantity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_VISION_MESSAGE_NED_POSES_H
