// Generated by gencpp from file amore_vision/to_cam.msg
// DO NOT EDIT!


#ifndef AMORE_VISION_MESSAGE_TO_CAM_H
#define AMORE_VISION_MESSAGE_TO_CAM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace amore_vision
{
template <class ContainerAllocator>
struct to_cam_
{
  typedef to_cam_<ContainerAllocator> Type;

  to_cam_()
    : x()
    , y()
    , quantity(0)  {
    }
  to_cam_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , quantity(0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _x_type;
  _x_type x;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _y_type;
  _y_type y;

   typedef int32_t _quantity_type;
  _quantity_type quantity;





  typedef boost::shared_ptr< ::amore_vision::to_cam_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amore_vision::to_cam_<ContainerAllocator> const> ConstPtr;

}; // struct to_cam_

typedef ::amore_vision::to_cam_<std::allocator<void> > to_cam;

typedef boost::shared_ptr< ::amore_vision::to_cam > to_camPtr;
typedef boost::shared_ptr< ::amore_vision::to_cam const> to_camConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amore_vision::to_cam_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amore_vision::to_cam_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::amore_vision::to_cam_<ContainerAllocator1> & lhs, const ::amore_vision::to_cam_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.quantity == rhs.quantity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::amore_vision::to_cam_<ContainerAllocator1> & lhs, const ::amore_vision::to_cam_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace amore_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::to_cam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amore_vision::to_cam_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::to_cam_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amore_vision::to_cam_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::to_cam_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amore_vision::to_cam_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amore_vision::to_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d855056e0e6fe3b83d73c1f04a752222";
  }

  static const char* value(const ::amore_vision::to_cam_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd855056e0e6fe3b8ULL;
  static const uint64_t static_value2 = 0x3d73c1f04a752222ULL;
};

template<class ContainerAllocator>
struct DataType< ::amore_vision::to_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amore_vision/to_cam";
  }

  static const char* value(const ::amore_vision::to_cam_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amore_vision::to_cam_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] x\n"
"float32[] y\n"
"int32 quantity\n"
;
  }

  static const char* value(const ::amore_vision::to_cam_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amore_vision::to_cam_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.quantity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct to_cam_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amore_vision::to_cam_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amore_vision::to_cam_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "quantity: ";
    Printer<int32_t>::stream(s, indent + "  ", v.quantity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMORE_VISION_MESSAGE_TO_CAM_H
