# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from amore_vision/grid_point.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class grid_point(genpy.Message):
  _md5sum = "435092f9725ac07bcd4486688f70bed6"
  _type = "amore_vision/grid_point"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 x 
float32 y
int8 status
int8 percent
int8 min_x 
int8 min_y
int8 max_x 
int8 max_y
float32 grid_size
"""
  __slots__ = ['x','y','status','percent','min_x','min_y','max_x','max_y','grid_size']
  _slot_types = ['float32','float32','int8','int8','int8','int8','int8','int8','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,status,percent,min_x,min_y,max_x,max_y,grid_size

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(grid_point, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.status is None:
        self.status = 0
      if self.percent is None:
        self.percent = 0
      if self.min_x is None:
        self.min_x = 0
      if self.min_y is None:
        self.min_y = 0
      if self.max_x is None:
        self.max_x = 0
      if self.max_y is None:
        self.max_y = 0
      if self.grid_size is None:
        self.grid_size = 0.
    else:
      self.x = 0.
      self.y = 0.
      self.status = 0
      self.percent = 0
      self.min_x = 0
      self.min_y = 0
      self.max_x = 0
      self.max_y = 0
      self.grid_size = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f6bf().pack(_x.x, _x.y, _x.status, _x.percent, _x.min_x, _x.min_y, _x.max_x, _x.max_y, _x.grid_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.x, _x.y, _x.status, _x.percent, _x.min_x, _x.min_y, _x.max_x, _x.max_y, _x.grid_size,) = _get_struct_2f6bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f6bf().pack(_x.x, _x.y, _x.status, _x.percent, _x.min_x, _x.min_y, _x.max_x, _x.max_y, _x.grid_size))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 18
      (_x.x, _x.y, _x.status, _x.percent, _x.min_x, _x.min_y, _x.max_x, _x.max_y, _x.grid_size,) = _get_struct_2f6bf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f6bf = None
def _get_struct_2f6bf():
    global _struct_2f6bf
    if _struct_2f6bf is None:
        _struct_2f6bf = struct.Struct("<2f6bf")
    return _struct_2f6bf
