# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from amore_vision/propulsion_system.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class propulsion_system(genpy.Message):
  _md5sum = "71d621936073a6985aace9a419610593"
  _type = "amore_vision/propulsion_system"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header
geometry_msgs/Point goal_position
std_msgs/Float64 goal_psi
geometry_msgs/Point usv_position
std_msgs/Float64 usv_psi
std_msgs/Float64 usv_latitude
std_msgs/Float64 usv_longitude
std_msgs/Float64 e_xy_allowed
std_msgs/Float64 e_psi_allowed

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: std_msgs/Float64
float64 data"""
  __slots__ = ['header','goal_position','goal_psi','usv_position','usv_psi','usv_latitude','usv_longitude','e_xy_allowed','e_psi_allowed']
  _slot_types = ['std_msgs/Header','geometry_msgs/Point','std_msgs/Float64','geometry_msgs/Point','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64','std_msgs/Float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,goal_position,goal_psi,usv_position,usv_psi,usv_latitude,usv_longitude,e_xy_allowed,e_psi_allowed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(propulsion_system, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.Point()
      if self.goal_psi is None:
        self.goal_psi = std_msgs.msg.Float64()
      if self.usv_position is None:
        self.usv_position = geometry_msgs.msg.Point()
      if self.usv_psi is None:
        self.usv_psi = std_msgs.msg.Float64()
      if self.usv_latitude is None:
        self.usv_latitude = std_msgs.msg.Float64()
      if self.usv_longitude is None:
        self.usv_longitude = std_msgs.msg.Float64()
      if self.e_xy_allowed is None:
        self.e_xy_allowed = std_msgs.msg.Float64()
      if self.e_psi_allowed is None:
        self.e_psi_allowed = std_msgs.msg.Float64()
    else:
      self.header = std_msgs.msg.Header()
      self.goal_position = geometry_msgs.msg.Point()
      self.goal_psi = std_msgs.msg.Float64()
      self.usv_position = geometry_msgs.msg.Point()
      self.usv_psi = std_msgs.msg.Float64()
      self.usv_latitude = std_msgs.msg.Float64()
      self.usv_longitude = std_msgs.msg.Float64()
      self.e_xy_allowed = std_msgs.msg.Float64()
      self.e_psi_allowed = std_msgs.msg.Float64()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12d().pack(_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_psi.data, _x.usv_position.x, _x.usv_position.y, _x.usv_position.z, _x.usv_psi.data, _x.usv_latitude.data, _x.usv_longitude.data, _x.e_xy_allowed.data, _x.e_psi_allowed.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.Point()
      if self.goal_psi is None:
        self.goal_psi = std_msgs.msg.Float64()
      if self.usv_position is None:
        self.usv_position = geometry_msgs.msg.Point()
      if self.usv_psi is None:
        self.usv_psi = std_msgs.msg.Float64()
      if self.usv_latitude is None:
        self.usv_latitude = std_msgs.msg.Float64()
      if self.usv_longitude is None:
        self.usv_longitude = std_msgs.msg.Float64()
      if self.e_xy_allowed is None:
        self.e_xy_allowed = std_msgs.msg.Float64()
      if self.e_psi_allowed is None:
        self.e_psi_allowed = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_psi.data, _x.usv_position.x, _x.usv_position.y, _x.usv_position.z, _x.usv_psi.data, _x.usv_latitude.data, _x.usv_longitude.data, _x.e_xy_allowed.data, _x.e_psi_allowed.data,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12d().pack(_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_psi.data, _x.usv_position.x, _x.usv_position.y, _x.usv_position.z, _x.usv_psi.data, _x.usv_latitude.data, _x.usv_longitude.data, _x.e_xy_allowed.data, _x.e_psi_allowed.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.goal_position is None:
        self.goal_position = geometry_msgs.msg.Point()
      if self.goal_psi is None:
        self.goal_psi = std_msgs.msg.Float64()
      if self.usv_position is None:
        self.usv_position = geometry_msgs.msg.Point()
      if self.usv_psi is None:
        self.usv_psi = std_msgs.msg.Float64()
      if self.usv_latitude is None:
        self.usv_latitude = std_msgs.msg.Float64()
      if self.usv_longitude is None:
        self.usv_longitude = std_msgs.msg.Float64()
      if self.e_xy_allowed is None:
        self.e_xy_allowed = std_msgs.msg.Float64()
      if self.e_psi_allowed is None:
        self.e_psi_allowed = std_msgs.msg.Float64()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.goal_position.x, _x.goal_position.y, _x.goal_position.z, _x.goal_psi.data, _x.usv_position.x, _x.usv_position.y, _x.usv_position.z, _x.usv_psi.data, _x.usv_latitude.data, _x.usv_longitude.data, _x.e_xy_allowed.data, _x.e_psi_allowed.data,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
